# file: scala/tasks/binaries.yml
- name: updating apt cache
  apt: update_cache=yes

- name: updating apt-get install
  shell: sudo apt-get install -f

- name: installing java7
  shell: sudo apt-get -y install default-jre

- name: Scala | Download sbt
  get_url:
    url: "http://dl.bintray.com/sbt/debian/sbt-{{scala_sbt_version}}.deb"
    dest: "/tmp/sbt-{{scala_sbt_version}}.deb"

- name: Scala | Install sbt
  command: "dpkg --skip-same-version -i /tmp/sbt-{{scala_sbt_version}}.deb"
  register: sbt_dpkg_result
  changed_when: "'already installed' not in sbt_dpkg_result.stderr"
